WITH table_0 AS (
  SELECT
    1 AS a,
    1 AS b
),
table_4 AS (
  WITH RECURSIVE loop AS (
    SELECT
      a,
      b
    FROM
      table_0 AS table_1
    UNION
    ALL
    SELECT
      b AS _expr_0,
      a + b
    FROM
      loop AS table_2
  )
  SELECT
    *
  FROM
    loop
)
SELECT
  a,
  b
FROM
  table_4 AS table_3
LIMIT
  7

-- Generated by PRQL compiler version:0.6.1 target:sql.duckdb (https://prql-lang.org)
